export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Создать макет главной страницы",
    date: "12.04.2024",
    status: "Без статуса",
    color: 'orange'
  },
  {
    id: 2,
    topic: "Research",
    title: "Исследовать рынок конкурентов",
    date: "12.04.2024",
    status: "Нужно сделать",
    color: 'green'
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Написать статью для блога",
    date: "12.04.2024",
    status: "В работе",
    color: 'purple'
  },
  {
    id: 4,
    topic: "Research",
    title: "Провести опрос среди целевой аудитории",
    date: "12.04.2024",
    status: "Тестирование",
    color: 'green'
  },
  {
    id: 5,
    topic: "Copywriting",
    title: "Редактировать и проконтролировать контент",
    date: "12.04.2024",
    status: "Готово",
    color: 'purple'
  },
  {
    id: 6,
    topic: "Web Design",
    title: "Разработка UI компонентов",
    date: "12.04.2024",
    status: "Без статуса",
    color: "orange",
  },
  {
    id: 7,
    topic: "Web Design",
    title: "Адаптация дизайна под мобильные устройства",
    date: "14.04.2024",
    status: "В работе",
    color: "orange",
  },
  {
    id: 8,
    topic: "Web Design",
    title: "Интеграция дизайна с CMS",
    date: "16.04.2024",
    status: "Готово",
    color: "orange",
  },
  {
    id: 9,
    topic: "Research",
    title: "Анализ тенденций в сфере веб-дизайна",
    date: "18.04.2024",
    status: "Нужно сделать",
    color: "purple",
  },
  {
    id: 10,
    topic: "Research",
    title: "Исследование поведенческих паттернов пользователей",
    date: "20.04.2024",
    status: "Тестирование",
    color: "purple",
  },
  {
    id: 11,
    topic: "Research",
    title: "Сравнительный анализ конкурентов",
    date: "22.04.2024",
    status: "Готово",
    color: "purple",
  },
  {
    id: 12,
    topic: "Copywriting",
    title: "Создание продающего контента для главной страницы",
    date: "24.04.2024",
    status: "В работе",
    color: "green",
  },
  {
    id: 13,
    topic: "Copywriting",
    title: "Разработка контент-плана для блога",
    date: "26.04.2024",
    status: "Тестирование",
    color: "green",
  },
  {
    id: 14,
    topic: "Copywriting",
    title: "SEO оптимизация контента",
    date: "28.04.2024",
    status: "Готово",
    color: "green",
  },
];
